# Array

Array is the collection of similar data type.


In [1]:
import numpy as np

In [3]:
arr = np.array([])

In [4]:
arr

array([], dtype=float64)

In [5]:
arr = np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr = np.array([1,2,3,4,"A"])

In [8]:
arr

array(['1', '2', '3', '4', 'A'], dtype='<U11')

In [11]:
arr = np.array([1,2,3,4], dtype = 'float')

In [12]:
arr

array([1., 2., 3., 4.])

In [13]:
arr

array([1., 2., 3., 4.])

In [14]:
arr.ndim

1

In [15]:
arr.size

4

In [16]:
arr.shape

(4,)

In [17]:
# creating 2d array

In [18]:
arr = np.array([[1,2,3],[4,5,6]])

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr.ndim

2

In [22]:
arr.size

6

In [23]:
arr.shape

(2, 3)

In [24]:
# arange : array range

In [25]:
arr = np.arange(10)

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr = np.arange(5,10,2)

In [28]:
arr

array([5, 7, 9])

In [29]:
np_arr = np.array([['Python',"R","Kotlin"],[len("Python"),len("R"),len("Kotlin")]])

In [30]:
np_arr

array([['Python', 'R', 'Kotlin'],
       ['6', '1', '6']], dtype='<U11')

In [31]:
np_arr[0]

array(['Python', 'R', 'Kotlin'], dtype='<U11')

In [32]:
np_arr[1]

array(['6', '1', '6'], dtype='<U11')

In [37]:
np_arr[0][0]

'Python'

In [38]:
np_arr[1][-1]

'6'

In [39]:
# how to create a random array with number

In [40]:
arr = np.random.randint(low = 10, high = 100, size = 48)

In [41]:
arr

array([47, 53, 97, 53, 80, 48, 70, 34, 95, 53, 76, 36, 28, 24, 34, 36, 54,
       28, 54, 34, 18, 28, 85, 85, 40, 61, 69, 12, 22, 14, 14, 14, 38, 46,
       36, 12, 62, 93, 38, 56, 81, 18, 94, 71, 15, 14, 10, 77])

In [53]:
lst = list(np.random.randint(low = 10, high = 100, size = 48))

In [54]:
print(lst)

[91, 86, 38, 80, 97, 76, 54, 78, 79, 86, 49, 66, 65, 57, 60, 25, 39, 58, 18, 81, 18, 83, 10, 83, 40, 44, 94, 27, 89, 60, 39, 85, 94, 51, 68, 22, 97, 95, 92, 90, 15, 81, 20, 23, 30, 54, 77, 95]


In [55]:
arr[arr > 90]

array([97, 95, 93, 94])

In [56]:
myarr = np.array(lst)

In [57]:
myarr[myarr > 90]

array([91, 97, 94, 94, 97, 95, 92, 95])

In [58]:
lst = list(np.random.randint(low = 10, high = 500, size = 100))

In [60]:
print(lst)

[395, 258, 342, 465, 93, 152, 63, 66, 14, 122, 470, 491, 219, 436, 81, 16, 300, 404, 46, 415, 141, 255, 82, 393, 347, 197, 144, 93, 156, 106, 224, 234, 183, 353, 125, 118, 298, 323, 51, 133, 208, 362, 125, 64, 412, 280, 343, 114, 197, 485, 56, 194, 163, 124, 108, 68, 429, 209, 467, 396, 231, 296, 472, 497, 315, 44, 179, 241, 244, 439, 59, 261, 302, 230, 158, 471, 375, 269, 288, 225, 140, 184, 94, 432, 204, 56, 374, 221, 306, 278, 80, 21, 112, 428, 135, 400, 160, 381, 123, 419]


In [61]:
arr = np.array(lst) # converting list into array

In [62]:
arr[(arr >= 100) & (arr <= 150)]

array([122, 141, 144, 106, 125, 118, 133, 125, 114, 124, 108, 140, 112,
       135, 123])

In [63]:
# Find out the index of each number between 100 and 150

### NumPy Where method

this function by default return the index of each item from the array.

In [64]:
np.where((arr >= 100) & (arr <= 150))

(array([ 9, 20, 26, 29, 34, 35, 39, 42, 47, 53, 54, 80, 92, 94, 98],
       dtype=int64),)

In [71]:
arr[35]

118

In [72]:
arr[np.where((arr >= 100) & (arr <= 150))]

array([122, 141, 144, 106, 125, 118, 133, 125, 114, 124, 108, 140, 112,
       135, 123])

In [73]:
arr

array([395, 258, 342, 465,  93, 152,  63,  66,  14, 122, 470, 491, 219,
       436,  81,  16, 300, 404,  46, 415, 141, 255,  82, 393, 347, 197,
       144,  93, 156, 106, 224, 234, 183, 353, 125, 118, 298, 323,  51,
       133, 208, 362, 125,  64, 412, 280, 343, 114, 197, 485,  56, 194,
       163, 124, 108,  68, 429, 209, 467, 396, 231, 296, 472, 497, 315,
        44, 179, 241, 244, 439,  59, 261, 302, 230, 158, 471, 375, 269,
       288, 225, 140, 184,  94, 432, 204,  56, 374, 221, 306, 278,  80,
        21, 112, 428, 135, 400, 160, 381, 123, 419])

In [75]:
arr[[0,5,8,9,0,8,9]]

array([395, 152,  14, 122, 395,  14, 122])

In [76]:
print(lst)

[395, 258, 342, 465, 93, 152, 63, 66, 14, 122, 470, 491, 219, 436, 81, 16, 300, 404, 46, 415, 141, 255, 82, 393, 347, 197, 144, 93, 156, 106, 224, 234, 183, 353, 125, 118, 298, 323, 51, 133, 208, 362, 125, 64, 412, 280, 343, 114, 197, 485, 56, 194, 163, 124, 108, 68, 429, 209, 467, 396, 231, 296, 472, 497, 315, 44, 179, 241, 244, 439, 59, 261, 302, 230, 158, 471, 375, 269, 288, 225, 140, 184, 94, 432, 204, 56, 374, 221, 306, 278, 80, 21, 112, 428, 135, 400, 160, 381, 123, 419]


In [77]:
x

TypeError: list indices must be integers or slices, not list

In [78]:
print(lst)

[395, 258, 342, 465, 93, 152, 63, 66, 14, 122, 470, 491, 219, 436, 81, 16, 300, 404, 46, 415, 141, 255, 82, 393, 347, 197, 144, 93, 156, 106, 224, 234, 183, 353, 125, 118, 298, 323, 51, 133, 208, 362, 125, 64, 412, 280, 343, 114, 197, 485, 56, 194, 163, 124, 108, 68, 429, 209, 467, 396, 231, 296, 472, 497, 315, 44, 179, 241, 244, 439, 59, 261, 302, 230, 158, 471, 375, 269, 288, 225, 140, 184, 94, 432, 204, 56, 374, 221, 306, 278, 80, 21, 112, 428, 135, 400, 160, 381, 123, 419]


In [82]:
arr[arr % 2 == 0]

array([258, 342, 152,  66,  14, 122, 470, 436,  16, 300, 404,  46,  82,
       144, 156, 106, 224, 234, 118, 298, 208, 362,  64, 412, 280, 114,
        56, 194, 124, 108,  68, 396, 296, 472,  44, 244, 302, 230, 158,
       288, 140, 184,  94, 432, 204,  56, 374, 306, 278,  80, 112, 428,
       400, 160])

In [83]:
arr[arr % 5 == 0]

array([395, 465, 470, 300, 415, 255, 125, 125, 280, 485, 315, 230, 375,
       225, 140,  80, 135, 400, 160])

In [85]:
arr[(arr % 5 == 0) & (arr % 15 == 0)]

array([465, 300, 255, 315, 375, 225, 135])

### How to append an array

In [86]:
arr = np.array([1,2,3])

In [87]:
np.append(arr = arr, values = 5)

array([1, 2, 3, 5])

In [90]:
arr = np.append(arr,[6,7,8,9,0])

### How we can delete the number from array 

### NumPy Delete

Using this function we can delete any item based on item's index.

In [91]:
arr

array([1, 2, 3, 6, 7, 8, 9, 0])

In [93]:
np.delete(arr,[2,-2])

array([1, 2, 6, 7, 8, 0])

In [94]:
newarray = np.array(lst)

In [95]:
newarray

array([395, 258, 342, 465,  93, 152,  63,  66,  14, 122, 470, 491, 219,
       436,  81,  16, 300, 404,  46, 415, 141, 255,  82, 393, 347, 197,
       144,  93, 156, 106, 224, 234, 183, 353, 125, 118, 298, 323,  51,
       133, 208, 362, 125,  64, 412, 280, 343, 114, 197, 485,  56, 194,
       163, 124, 108,  68, 429, 209, 467, 396, 231, 296, 472, 497, 315,
        44, 179, 241, 244, 439,  59, 261, 302, 230, 158, 471, 375, 269,
       288, 225, 140, 184,  94, 432, 204,  56, 374, 221, 306, 278,  80,
        21, 112, 428, 135, 400, 160, 381, 123, 419])

In [96]:
np.where(newarray % 2 == 0)

(array([ 1,  2,  5,  7,  8,  9, 10, 13, 15, 16, 17, 18, 22, 26, 28, 29, 30,
        31, 35, 36, 40, 41, 43, 44, 45, 47, 50, 51, 53, 54, 55, 59, 61, 62,
        65, 68, 72, 73, 74, 78, 80, 81, 82, 83, 84, 85, 86, 88, 89, 90, 92,
        93, 95, 96], dtype=int64),)

In [97]:
np.delete(newarray, np.where(newarray % 2 == 0))

array([395, 465,  93,  63, 491, 219,  81, 415, 141, 255, 393, 347, 197,
        93, 183, 353, 125, 323,  51, 133, 125, 343, 197, 485, 163, 429,
       209, 467, 231, 497, 315, 179, 241, 439,  59, 261, 471, 375, 269,
       225, 221,  21, 135, 381, 123, 419])

In [98]:
arr

array([1, 2, 3, 6, 7, 8, 9, 0])

In [99]:
arr[0]

1

In [100]:
arr[0] = 100

In [101]:
arr

array([100,   2,   3,   6,   7,   8,   9,   0])

In [102]:
arr = np.array([[1,2,3],[4,5,6]])

In [108]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
np.append(arr, 10)

array([ 1,  2,  3,  4,  5,  6, 10])

In [112]:
newarr = np.array([7,8,9])

In [113]:
np.append(arr, newarr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.append(arr, newarr, axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [116]:
arr1 = np.array([[5,6,7],[7,8,0]])

In [117]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr1

array([[5, 6, 7],
       [7, 8, 0]])

In [119]:
np.append(arr, arr1)

array([1, 2, 3, 4, 5, 6, 5, 6, 7, 7, 8, 0])

In [120]:
np.append(arr, arr1, axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7],
       [7, 8, 0]])

In [121]:
np.concatenate((arr, arr1), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7],
       [7, 8, 0]])

In [122]:
np.concatenate((arr, arr1), axis = 1)

array([[1, 2, 3, 5, 6, 7],
       [4, 5, 6, 7, 8, 0]])

In [125]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.append(arr, "Suman")

array(['1', '2', '3', '4', '5', '6', 'Suman'], dtype='<U11')

### numpy mathmatical opeations

In [128]:
jan_revenue = np.array([345,67,89,56.78])
feb_revenue = np.array([56,78,90,45.6])

In [129]:
jan_revenue + feb_revenue

array([401.  , 145.  , 179.  , 102.38])

In [130]:
jan_revenue - feb_revenue

array([289.  , -11.  ,  -1.  ,  11.18])

In [131]:
a = np.array([[5,-6],[-4,6]])
b = np.array([[4,6],[5,8]])

In [132]:
np.add([1,2,3],[5,6,7])

array([ 6,  8, 10])

In [133]:
a - b

array([[  1, -12],
       [ -9,  -2]])

In [134]:
a + b

array([[ 9,  0],
       [ 1, 14]])

In [135]:
a * b

array([[ 20, -36],
       [-20,  48]])

In [136]:
np.sum(feb_revenue)

269.6

In [137]:
np.mean(jan_revenue)

139.445

In [138]:
arr = np.array([4,5,6,7,8,9])

In [139]:
arr

array([4, 5, 6, 7, 8, 9])

In [140]:
np.sqrt(arr)

array([2.        , 2.23606798, 2.44948974, 2.64575131, 2.82842712,
       3.        ])

In [141]:
np.square(arr)

array([16, 25, 36, 49, 64, 81])

In [142]:
# how to reshape of array

In [143]:
arr = np.arange(48).reshape(4,12)

In [144]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [146]:
arr = np.arange(64).reshape(4,4,4)

In [147]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [148]:
arr = np.arange(64).reshape(2,4,4,2)

In [149]:
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]],


       [[[32, 33],
         [34, 35],
         [36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59],
         [60, 61],
         [62, 63]]]])

In [150]:
arr.shape

(2, 4, 4, 2)

In [151]:
arr.ndim

4

In [152]:
arr.size

64

In [153]:
arr.dtype

dtype('int32')

In [161]:
arr = np.array([2,3,4,5,6,7,8,9,2,3,4,5,6,7,8,9])

In [165]:
len(arr)

16

In [166]:
np.split(arr,4)

[array([2, 3, 4, 5]),
 array([6, 7, 8, 9]),
 array([2, 3, 4, 5]),
 array([6, 7, 8, 9])]

In [168]:
np.split(arr,[2,4,9])

[array([2, 3]),
 array([4, 5]),
 array([6, 7, 8, 9, 2]),
 array([3, 4, 5, 6, 7, 8, 9])]

In [183]:
lst = np.random.randint(10,1000,100)

In [184]:
print(lst)

[460 260 528 532 427 760 665 953 443 495 822 243 487 200 787 116 759 814
 147 761  63 908 103 746 933 239 356 732 332 586 726  25 737 950 281 204
 377 107  66 245 396 242 640 140 619 569 997 404 681 282 224 170 240  93
 403 939 237 235 607 431 674 115 949  33 379 969 147 982  62 601 461 769
 844 588 525 209 651 205 612 368 252 441 274 630 171 534 119 327 638 973
 916 645 593  91  15 603 244 990 115 802]


In [186]:
np.where(lst <= 500,"-", lst)

array(['-', '-', '528', '532', '-', '760', '665', '953', '-', '-', '822',
       '-', '-', '-', '787', '-', '759', '814', '-', '761', '-', '908',
       '-', '746', '933', '-', '-', '732', '-', '586', '726', '-', '737',
       '950', '-', '-', '-', '-', '-', '-', '-', '-', '640', '-', '619',
       '569', '997', '-', '681', '-', '-', '-', '-', '-', '-', '939', '-',
       '-', '607', '-', '674', '-', '949', '-', '-', '969', '-', '982',
       '-', '601', '-', '769', '844', '588', '525', '-', '651', '-',
       '612', '-', '-', '-', '-', '630', '-', '534', '-', '-', '638',
       '973', '916', '645', '593', '-', '-', '603', '-', '990', '-',
       '802'], dtype='<U11')

In [154]:
import pandas as pd

In [155]:
df = pd.read_csv("Superstore.csv", encoding = "ISO-8859-1")

In [156]:
df.shape

(9994, 21)

In [159]:
newdf = df[['Order ID',"Region","Category",'Sub-Category',"State","Sales","Quantity"]].copy()

In [160]:
newdf.head()

Order ID Region         Category Sub-Category       State     Sales  \
0  CA-2016-152156  South        Furniture    Bookcases    Kentucky  261.9600   
1  CA-2016-152156  South        Furniture       Chairs    Kentucky  731.9400   
2  CA-2016-138688   West  Office Supplies       Labels  California   14.6200   
3  US-2015-108966  South        Furniture       Tables     Florida  957.5775   
4  US-2015-108966  South  Office Supplies      Storage     Florida   22.3680   

   Quantity  
0         2  
1         3  
2         2  
3         5  
4         2

### Numpy tutorial:

https://www.youtube.com/watch?v=AqJMw61d7CA&list=PLWuFHho1zKhUGq1be3zUT3Ek5myJrKiIP

### Pandas Live Case Study of Uber's data:
https://www.youtube.com/watch?v=zLYC_Py_rk4

In [170]:
newdf.head()

Order ID Region         Category Sub-Category       State     Sales  \
0  CA-2016-152156  South        Furniture    Bookcases    Kentucky  261.9600   
1  CA-2016-152156  South        Furniture       Chairs    Kentucky  731.9400   
2  CA-2016-138688   West  Office Supplies       Labels  California   14.6200   
3  US-2015-108966  South        Furniture       Tables     Florida  957.5775   
4  US-2015-108966  South  Office Supplies      Storage     Florida   22.3680   

   Quantity  
0         2  
1         3  
2         2  
3         5  
4         2

* sales -> 0 - 500 : sales 0 - 500
* sales 500 - 1000 : sales 500 - 1000
* sales 1000 - 5000 : sales 1000 - 5000
* sales > 5000 : sales > 5000

In [171]:
def sales_bucket(s):
    if s >= 0 and s <= 500:
        return "sales 0 - 500"
    elif s > 500 and s <= 1000:
        return "sales 500 - 1000"
    elif s > 1000 and s <= 5000:
        return "sales 1000 - 5000"
    else:
        return 'sales > 5000'

In [175]:
sales_bucket(11995)

'sales > 5000'

In [178]:
%%time
newdf["SalesBucket"] = newdf.apply(lambda x : sales_bucket(x['Sales']), axis = 1)

CPU times: total: 125 ms
Wall time: 128 ms


In [177]:
newdf.head()

Order ID Region         Category Sub-Category       State     Sales  \
0  CA-2016-152156  South        Furniture    Bookcases    Kentucky  261.9600   
1  CA-2016-152156  South        Furniture       Chairs    Kentucky  731.9400   
2  CA-2016-138688   West  Office Supplies       Labels  California   14.6200   
3  US-2015-108966  South        Furniture       Tables     Florida  957.5775   
4  US-2015-108966  South  Office Supplies      Storage     Florida   22.3680   

   Quantity       SalesBucket  
0         2     sales 0 - 500  
1         3  sales 500 - 1000  
2         2     sales 0 - 500  
3         5  sales 500 - 1000  
4         2     sales 0 - 500

In [182]:
# newdf["SalesBucket"].value_counts().plot(kind='barh')

In [196]:
%%time
newdf["Sales_Bucket"] = np.where((newdf['Sales'] >= 0) & (newdf['Sales'] <= 500),"Sales 0 - 500",
                    np.where((newdf['Sales'] >500) & (newdf['Sales'] <= 1000),
                            "Sales 500 - 1000","Sales > 1000"))


CPU times: total: 15.6 ms
Wall time: 5.98 ms


In [195]:
newdf.head()

Order ID Region         Category Sub-Category       State     Sales  \
0  CA-2016-152156  South        Furniture    Bookcases    Kentucky  261.9600   
1  CA-2016-152156  South        Furniture       Chairs    Kentucky  731.9400   
2  CA-2016-138688   West  Office Supplies       Labels  California   14.6200   
3  US-2015-108966  South        Furniture       Tables     Florida  957.5775   
4  US-2015-108966  South  Office Supplies      Storage     Florida   22.3680   

   Quantity       SalesBucket      Sales_Bucket  
0         2     sales 0 - 500     Sales 0 - 500  
1         3  sales 500 - 1000  Sales 500 - 1000  
2         2     sales 0 - 500     Sales 0 - 500  
3         5  sales 500 - 1000  Sales 500 - 1000  
4         2     sales 0 - 500     Sales 0 - 500

In [197]:
newdf.shape

(9994, 9)